name: Deploy to S3

on:
  push:
    branges:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest

    env:
      AWS_EC2_METADATA_DISABLED: true    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update
        run: |
          sudo apt-get update

      - name: Install Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10'

      - name: Install mkdocs
        run: pip install mkdocs-material
      
      - name: Build documentation
        run: mkdocs build

      - name: Sync with S3
        run: | 
          aws s3 sync site/ s3://${{ secrets.AWS_BUCKET_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          
